[mysqld]
port=3306
basedir=C:/Program Files/MySQL/MySQL Server 8.4
datadir=C:/Users/m1913/mysql-data/xuance-mysql-8.4
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci

[client]
port=3306
default-character-set=utf8mb4
